[tool.poetry]
name = "addpage"
version = "0.0.4"
description = "`addpage` is a package for adding page number to PDF file."
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
homepage = "https://github.com/SaitoTsutomu/addpage"
classifiers = [
   "Development Status :: 1 - Planning",
   "License :: OSI Approved :: Python Software Foundation License",
   "Programming Language :: Python",
   "Topic :: Software Development",
   "Topic :: Scientific/Engineering",
]
license = "PSFL"
readme = "README.rst"

[tool.poetry.scripts]
addpage = "addpage:main"

[tool.poetry.dependencies]
python = "^3.7"
PyPDF2 = "^1.26.0"
reportlab = "^3.5.42"
pdfformfiller = "^0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
black = "^19.10b0"
isort = "^4.3.21"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
